# Generated by Django 5.2.5 on 2025-11-09 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("quantity", models.PositiveIntegerField()),
                ("unitPrice", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "taxPercent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=30, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128)),
                (
                    "phone",
                    models.CharField(blank=True, default="", max_length=15, null=True),
                ),
                (
                    "businessName",
                    models.CharField(default="", max_length=50, unique=True),
                ),
                ("address", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoiceNumber", models.CharField(max_length=20, unique=True)),
                ("invoiceDate", models.DateField(auto_now_add=True)),
                ("dueDate", models.DateField(blank=True, null=True)),
                ("businessName", models.CharField(max_length=100)),
                ("businessEmail", models.EmailField(max_length=100)),
                ("businessAddress", models.TextField()),
                ("businessPhone", models.CharField(max_length=15)),
                ("clientName", models.CharField(max_length=100)),
                ("clientEmail", models.EmailField(max_length=100)),
                ("clientAddress", models.TextField()),
                ("clientPhone", models.CharField(max_length=15)),
                ("notes", models.TextField(blank=True, null=True)),
                ("paymentTerms", models.CharField(default="Net 15", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[("Paid", "Paid"), ("Unpaid", "Unpaid")],
                        default="Unpaid",
                        max_length=10,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "taxTotal",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "items",
                    models.ManyToManyField(related_name="invoices", to="invoice.item"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="invoice.user",
                    ),
                ),
            ],
        ),
    ]
