# Generated by Django 5.2.5 on 2025-11-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0002_alter_invoice_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="total",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
